# Generated by Django 5.1.6 on 2025-04-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
