# Generated by Django 5.1.6 on 2025-04-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_cafe_average_rating_cafe_total_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='image',
            field=models.TextField(default='no_image_available'),
        ),
        migrations.AddField(
            model_name='cafe',
            name='route',
            field=models.TextField(default='no_route_available'),
        ),
    ]
