# Generated by Django 5.1.6 on 2025-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0003_cafe_image_cafe_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
