# Generated by Django 5.1.6 on 2025-04-08 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0005_alter_cafe_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='services',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='social_media',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
