# Generated by Django 5.1.6 on 2025-04-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0006_alter_cafe_about_alter_cafe_menu_alter_cafe_services_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='opening_hours',
            field=models.CharField(default='Not specified', max_length=255),
        ),
    ]
